### ISSUE TITLE
Remove things we don't need from conf and bin

### ISSUE THREAD

**Issue by stevenday** [mysociety/mapit.mysociety.org#1]
I've copied these folders directly from the mapit repo, there's probably stuff in there that we don't need. Off the top of my head:

sysvinit.example
all the various packages.xxx (we could just keep the bare `packages`)

**Comment by dracos** [comment]
I don't think the account/base.html is needed - all the children seem to include the `article` that is the only difference? Could the CSS line be done with extra_css?
