### ISSUE TITLE
Changes to sign-up form

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/mapit.mysociety.org#100]
https://mapit.mysociety.org/account/signup/

At the moment there's a field for non-profit making users to describe their project. If they tick 'charity' the same field asks for their charity number; if they don't qualify for a discount we don't ask them anything at all.

![Screenshot_2019-05-23 Sign up - MapIt](https://user-images.githubusercontent.com/944656/58239343-ca7bca00-7d40-11e9-90cb-81d154c0131b.png)

- Please can we make the 'please provide details of your project' apply to every sign-up, charity, commercial or not commercial? 
- It's currently mandatory for those ticking 'non -commercial' but we could make it non-mandatory for others.
- We'll still need to ask for the charity number for charities
- Also include a tickbox: "We like to write about interesting uses of MapIt on the mySociety blog. Please tick here if you are happy for us to get in touch for this purpose'.

**Comment by dracos** [comment]
It now always ask for details optionally, and have added tickbox about getting in contact.
