### ISSUE TITLE
Update Stripe statement descriptor

### ISSUE THREAD

**Issue by abibroom** [mysociety/mapit.mysociety.org#114]
When I export a CSV file of recent payments from Stripe, the `Statement Descriptor` column for MapIt payments contains `mySociety` and it should now be `SocietyWorks`.

I don't _think_ this is something that I can change through Stripe admin, though I could be wrong; my reason for thinking it's in the code is that the other services we charge for don't have a statement descriptor.

**Comment by abibroom** [comment]
(I guess we don't have to set a statement descriptor here at all, it could just be left blank like TWFY/WDTK do.)

**Comment by dracos** [comment]
Found bit in admin that did it
