### ISSUE TITLE
Data source for WMCF areas?

### ISSUE THREAD

**Issue by torotil** [mysociety/mapit.mysociety.org#152]
I saw that you added the constituencies for the upcoming parliamentary election. Now I’m wondering where you got the boundaries from. I looked around a bit but couldn’t find an obvious source. Could you point it out to me?

**Comment by dracos** [comment]
This concerns our mapit.mysociety.org, not the core code, so have transferred the issue there.
Hopefully https://www.mysociety.org/2023/09/12/navigating-the-new-constituencies/ has all the details you're after.
