### ISSUE TITLE
Add guidance to /account/signup/ and account/login pages

### ISSUE THREAD

**Issue by BenJam** [mysociety/mapit.mysociety.org#18]
Currently these pages make sense if you link to them from /#general but a user might land on them directly, in which case we should add some guidance here both from a legal and a UX standpoint. 

Deferring to @MyfanwyNixon but something like

> We recommend that you register for an account and obtain an api key if you're going to use the API. Anonymous usage of the API is permitted, but is rate limited to 10 calls a minute. The free usage limit for non-profit users is 50,000 calls to the API per year. All other uses need to acquire a licence.
> 
> Find out if you need a licence or get in touch so we can discuss how we can provide you with the service you require.

**Comment by MyfanwyNixon** [comment]
As far as I can understand the context _myself_ without seeing this in situ, this looks completely fine to me.

**Comment by stevenday** [comment]
@BenJam, @MyfanwyNixon - I've put this text up now if you want to check it in-situ. e.g. http://steve.mapit.dev.mysociety.org/account/signup/

**Comment by MyfanwyNixon** [comment]
:+1: Looks good to me

**Comment by stevenday** [comment]
Thanks @MyfanwyNixon - I'll close this then.
