### ISSUE TITLE
Add usage tracking

### ISSUE THREAD

**Issue by dracos** [mysociety/mapit.mysociety.org#25]
Following from #15 we would like to track individual users accounts, generating a daily email or viewable on a dashboard. Email should include key, registered email address and additional information from #24.

**Comment by stevenday** [comment]
Presumably this means tracking the number of hits too, which will mean adding some more counters to the Redis db used in #15 - allowing us to count usage by day, month, year? Currently we only store enough info to do the rate limiting. What reporting intervals will be needed? (We'll have to decide them up front to store them in Redis efficiently)
