### ISSUE TITLE
Review Terms/Licence/EULA/SLAs

### ISSUE THREAD

**Issue by BenJam** [mysociety/mapit.mysociety.org#27]
following #26

**Comment by abibroom** [comment]
[Initial draft](https://docs.google.com/document/d/1FU8ovMJQk34wGq2Ssmpak_zZmS9Ty-sAbIZvO_T95ek/edit#) still very much WIP.

**Comment by abibroom** [comment]
For reference, Mailchimp's pages (https://mailchimp.com/legal/) are really well-written and the tone is layman-friendly rather than legal.
