### ISSUE TITLE
Add approval of charitable status requests

### ISSUE THREAD

**Issue by abibroom** [mysociety/mapit.mysociety.org#41]
At the moment the workflow is:

customer adds charitable discount to subscription -> active immediately -> we can check and remove

Preferred would be:

customer submits request for charitable discount -> we are alerted to check and approve -> only then is the discount activated

This does create some issues around charging and payment - the specific one I can think of is if we take money off someone immediately on signup and they subsequently get 100% charitable discount approved, we're into refunds territory. Maybe a grace period is needed before the first charge is taken?

**Comment by dracos** [comment]
We could add a free trial period, though I would think that that is open to more abuse than this ticket is potentially worried about. I'm not sure if this is needed, really; checking regularly seems fine, given if they've tried to say they are and they aren't, we can charge them (if they've signed up for free tier, we can ask for payment/block them until then); if they say they aren't and they are, we can make them free/50% from then on and could return whatever money if wanted, either as a refund or by reducing their next invoice.
