### ISSUE TITLE
Too hard to find log in / sign up

### ISSUE THREAD

**Issue by abibroom** [mysociety/mapit.mysociety.org#6]
I didn't even notice any difference from the normal MapIt site. Account management stuff should be at the top of the page in the header.

**Comment by stevenday** [comment]
I think I need some design help with this one. The header is already quite wordy and there's enough different things going on that I don't feel confident making a decent space for these to sit on their own.

I've added a new sentence that hopefully improves things for now, until we have time to approach the design in a more holistic manner. It now looks like:

![screen shot 2015-09-25 at 15 17 30](https://cloud.githubusercontent.com/assets/663700/10102853/b924ee0a-6398-11e5-833d-36b7cd59eee3.png)

**Comment by stevenday** [comment]
Done in 027de668e99ea0a889e727f149a988f835e9b101
