### ISSUE TITLE
Populate the "description" field on Stripe invoices

### ISSUE THREAD

**Issue by abibroom** [mysociety/mapit.mysociety.org#71]
Now that we (hopefully will!) have Alaveteli payments coming in as well, it becomes important that I can tell the difference. At the moment we don't populate the 'Description' field shown below:

![stripedesc](https://user-images.githubusercontent.com/560001/33334141-ddd0c996-d460-11e7-9fd6-84256c6165d9.png)

-- this is the important one that comes out in the data export I use for accounting purposes.

I've been liaising with @garethrees about putting some useful text in here for the Alaveteli payments, so at least it will be possible to assume that no description = MapIt, and also you can manually add a description, but I'd prefer the computers to fill it in with e.g. "MapIt".

Alaveteli-side investigations suggested this has to be done in response to a webhook.

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli-professional/issues/371#issuecomment-346852432

**Comment by dracos** [comment]
It is actually the 'charge' description that appears in the CSV export, not the invoice description. So you'll need to fetch the charge ID given in the invoice object and update its description.
