### ISSUE TITLE
Signup form field ordering

### ISSUE THREAD

**Issue by abibroom** [mysociety/mapit.mysociety.org#8]
I would find this a more intuitive ordering of the fields:

Username
Email address
Password
Password (again)

(discuss: do we need username at all, i.e. can email address be the username?)

**Comment by stevenday** [comment]
I think the email address could easily be the username, the only advantage would be if you wanted allow people to register multiple accounts to an email address (they don't _have_ to be unique) or allow people to change their email address. I don't think either is very likely (or insurmountable by other means), and it is certainly the norm for a lot of services.

http://django-user-accounts.readthedocs.org/en/latest/usage.html#using-email-address-for-authentication is the documentation on how to do this with the user account system we have.

**Comment by stevenday** [comment]
Fixed in d15b7b1 and 94a86df
