### ISSUE TITLE
Broken links for marker images

### ISSUE THREAD

**Issue by sagepe** [mysociety/mapit.mysociety.org#81]
When viewing the results page for a postcode lookup there's a broken image link for the marker-icon. The bad link appears to be `https://mapit.mysociety.org/static/mapit/leaflet/images/marker-icon.2273e3d8ad92.png%22)marker-icon.png`. Looks like there are similar issues for some other assets too, e.g. `marker-icon-2x.png` and `marker-shadow.png`.

**Comment by dracos** [comment]
I fixed this in core in mysociety/mapit@2cc55312c6c5cd47c706d7e57e43096809af554c
Same fix needed here, applied in a94a2887e4e84413778ec953a745fe4ff925ae88, thanks.
