### ISSUE TITLE
Provide ability for customers to download their invoices

### ISSUE THREAD

**Issue by abibroom** [mysociety/mapit.mysociety.org#87]
Payment receipts are emailed to customers, but invoices aren't, some customers prefer to have the invoice.

Stripe provide a downloadable PDF for each invoice - show a page to logged-in customer listing their previous invoices so that they can save copies.

**Comment by abibroom** [comment]
@struan draws my attention to https://stripe.com/docs/billing/subscriptions/customer-portal which basically does this. Almost certainly more work to implement, but equally, probably saves time in the longer term as we benefit from the improvements they will make for us.

**Comment by dracos** [comment]
Done in 9dab7ce88d97a1248b5d0eec02e115a23d5e5faa anyway.
