### ISSUE TITLE
Change links to case studies

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/mapit.mysociety.org#95]
The Prostate Cancer site linked to on the homepage and on https://mapit.mysociety.org/overview is no longer active. We can change the link to the [blog post we wrote about it](https://www.mysociety.org/democracy/writetothem-for-campaigners/writetothem/standing-up-for-erectile-dysfunction-care-a-digital-empowerment-tool/).

For consistency we might as well also link to the [blog post about SocialCareInfo](https://www.mysociety.org/2016/01/22/how-socialcareinfo-matches-people-to-resources/).

And possibly write a blog post about Gov.uk's usage.

Pepysrd (on /overview) is also a dead link. For now we could replace it with SocialCareInfo but it's worth trying to find some more case studies where it's easy to see the part that MapIt plays.

**Comment by MyfanwyNixon** [comment]
Unassigned myself because I realised I'm not confident about replacing the images.

**Comment by dracos** [comment]
I don't think the images need replacing, happy to accept a PR changing whatever links.
