### ISSUE TITLE
Set up paid Adwords for MapIt

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/mapit.mysociety.org#97]
Contrary to many of our services, MapIt is a prime example of something that people would Google for when they need it. 
@markcridge Can we assign a trial budget of, say, £20 a month for three months to see if it brings a ROI? (We can't use our Adwords grant as it's commercial).
Perhaps trawl through emails and relevant mailing lists to see what sort of keywords people use when describing such a service.

**Comment by markcridge** [comment]
Yes, I think we can easily justify some test spend. Let's see how quickly that goes and we can up if it's having results.

**Comment by MyfanwyNixon** [comment]
Thanks - ok Adwords set up for the bulk spreadsheet tool and for the main MapIt API, and set to run for three months. I will have a look at it in a week to see how the various keywords are performing.
Meanwhile I'm going to open a ticket for putting a tracking code on the signup success page.
