### ISSUE TITLE
CCG data

### ISSUE THREAD

**Issue by torotil** [mysociety/mapit.mysociety.org#99]
I’d like to reproduce the CCG dataset that’s available on mapit.mysociety.org.

- Which data source are you using for this dataset?
- Are there reasons for not including it in the open source repo (other than https://github.com/mysociety/mapit/pull/74)?

I’m happy to help out if needed.

**Comment by dracos** [comment]
[We have a separate repo for mapit.mysociety.org, I have transferred your issue.]

> Which data source are you using for this dataset?

For England, it is the CCG release as given at https://data.gov.uk/dataset/91b301b2-ecfa-4066-9a2b-59511264ff76/ccg-map ; for Scotland, Wales, NI, it is their boundaries as of 2016 when they were imported. We should get them updated at some point, it hasn't been part of our regular updating. I don't think S/W/N have changed beyond minor tweaks, but England has changed quite a bit, I realise.

> Are there reasons for not including it in the open source repo

Do you mean http://parlvid.mysociety.org/os/? That is there because OS demand personal details in order to access the open data (plus historically/originally they were under a lot of demand so I threw it up as a help); CCG data is freely available for download from http://geoportal.statistics.gov.uk/ so I don't see a need for a mirror.

**Comment by torotil** [comment]
> [We have a separate repo for mapit.mysociety.org, I have transferred your issue.]

Great and thanks! I couldn’t find any import scripts in this repo though.

> For England, it is the CCG release as given at https://data.gov.uk/dataset/91b301b2-ecfa-4066-9a2b-59511264ff76/ccg-map ;

Great!

> for Scotland, Wales, NI, it is their boundaries as of 2016 when they were imported. We should get them updated at some point, it hasn't been part of our regular updating.

Do you mean their WMC boundaries? I did look up a few postcodes (on mapit.mysociety.org) and at least for one NI-postcode it did match its WMC constituency. For 3 scottish postcodes I didn’t get a CCG area at all.

> CCG data is freely available for download from http://geoportal.statistics.gov.uk/ so I don't see a need for a mirror.

I also don’t see the need for a mirror in this case. The data on the page is however the only place that tells me which data source is being used in the live instance. That’s why I was asking.

**Comment by dracos** [comment]
> Great and thanks! I couldn’t find any import scripts in this repo though.

It used the standard `mapit_import` script, no special code was necessary, as far as I can tell.

> Do you mean their WMC boundaries?

No, each constituent country has their own style of health board (England CCG, Wales WLHB, Scotland SHB, Northern Ireland NIHT). Boundaries for them are available from  http://geoportal.statistics.gov.uk/ (England and Wales), https://spatialdata.gov.scot/ (Scotland), and https://www.opendatani.gov.uk/ (NI) - hmm, perhaps *is* worth having a copy on our mirror!

**Comment by torotil** [comment]
I see. Thanks a lot for taking the time to answer all my questions!

**Comment by torotil** [comment]
I hope it’s OK if I post this related question in here. It seems importing the files is not as straight forward as we thought.

I’ve downloaded the KML file for CCGs from the link above. In the file the area codes are rendered as HTML inside the `Placemark/description` element. What should I pass to `--name_field` and `--code_field` to the `mapit_import` command?

I already tried pre-processing the file to have the code and name as explicit XML elements, but they don’t seem to be picked up by the import.

How did you do it for mapit.mysociety.org?

**Comment by torotil** [comment]
Ok, I think I’ve solved that by putting the data into the name and description XML-elements (instead of adding custom XML-elements) using the script below.

Then I can import the data using:

```
./manage.py mapit_import --country_code=E --area_type_code=CCG --code_field=description --name_field=name --code_type=ccg --name_type_code=NHS --generation_id=1 ../data/CCG_BSC_Apr2015-cleaned.KML --commit
```

-----

Script for preprocessing the KML file:

```python
import sys

import click
import lxml.etree


html = lxml.etree.HTMLParser()


KML_NAMESPACE='http://earth.google.com/kml/2.1'


@click.command()
@click.option('--input-file', type=click.File('r'), default=sys.stdin)
@click.option('--output-file', type=click.File('wb'), default=sys.stdout.buffer)
def transform_ccg(input_file, output_file):
    nsmap = {'kml': KML_NAMESPACE}

    tree = lxml.etree.parse(input_file)
    root = tree.getroot()
    for area in root.xpath('.//kml:Placemark', namespaces=nsmap):
        name = area.xpath('./kml:name', namespaces=nsmap)[0]
        description = area.xpath('./kml:description', namespaces=nsmap)[0]
        sub_root = lxml.etree.HTML(description.text)
        data = {}
        for tr in sub_root.xpath('//tr'):
            key, value = [td.text for td in tr.xpath('./td')]
            data[key] = value

        name.text = data['CCGname_short']
        description.text = data['CCGcode']

    tree.write(output_file, pretty_print=True)


if __name__ == '__main__':
    transform_ccg()
```

**Comment by torotil** [comment]
The newer files from http://geoportal.statistics.gov.uk/ don’t have this problem and can be imported directly. I was able to get all the data in with:

```
./manage.py mapit_import --country_code=E --area_type_code=CCG --code_field=ccg17cd --name_field=ccg17nm --code_type=ccg --name_type_code=NHS --generation_id=1 ../data/Clinical_Commissioning_Groups_April_2017_Full_Clipped_Boundaries_in_England_V4.shp --commit
./manage.py mapit_import --country_code=W --area_type_code=WLHB --code_field=lhb19cd --name_field=lhb19nm --code_type=nhsw --name_type_code=NHS --generation_id=1 ../data/Local_Health_Boards_April_2019_Boundaries_WA_BFC.kml --commit
./manage.py mapit_import --country_code=S --area_type_code=SHB --code_field=HBCode --name_field=HBName --code_type=nhss --name_type_code=NHS --generation_id=1 ../data/SG_NHS_HealthBoards_2019.shp --commit
./manage.py mapit_import --country_code=N --area_type_code=NIHT --code_field=TrustCode --name_field=TrustName --code_type=nhsn --name_type_code=NHS --generation_id=1 ../data/2017trustBoundary/dohTrustBoundary.shp --commit
```

**Comment by dracos** [comment]
Good to know. I've just imported the latest into mapit.mysociety.org, which was basically the same commands as you gave: https://github.com/mysociety/mapit.mysociety.org/issues/115#issuecomment-655588770
Think we can consider this closed.
